# Generated by Django 4.2.16 on 2024-11-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='age',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='lawyers',
            name='age',
        ),
        migrations.RemoveField(
            model_name='lawyers',
            name='gender',
        ),
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('L', 'laki-laki'), ('P', 'perempuan')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='nik',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lawyers',
            name='experience_years',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lawyers',
            name='license_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lawyers',
            name='specialization',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
