# Generated by Django 4.2.16 on 2024-12-15 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0002_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversations',
            name='case_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_case', to='cases.cases'),
        ),
        migrations.AddField(
            model_name='conversations',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_client', to='users.clients'),
        ),
        migrations.AddField(
            model_name='conversations',
            name='lawyer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_lawyer', to='users.lawyers'),
        ),
    ]
